/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Class;

import Traduction.JC_LanguageManager;
import com.formdev.flatlaf.FlatLightLaf;
import java.awt.Color;
import java.awt.Font;
import java.util.Locale;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.SwingConstants;
import javax.swing.UIManager;


/**
 *
 * @author migue
 */
public final class JF_Login extends javax.swing.JFrame {

    final String password = "uwjdclvzkeehmtur";
    final String email = "ejempjava@gmail.com";

    public JF_Login() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jP_Login = new javax.swing.JPanel();
        jL_Login = new javax.swing.JLabel();
        JL_UserTittle = new javax.swing.JLabel();
        JL_PaswordTittle = new javax.swing.JLabel();
        jB_SigIn = new javax.swing.JButton();
        jTF_Email = new javax.swing.JTextField();
        jTF_SpaceBlank1 = new javax.swing.JTextField();
        jTF_SpaceBlank2 = new javax.swing.JTextField();
        jPF_Password = new javax.swing.JPasswordField();
        jL_Validation = new javax.swing.JLabel();
        jMB_Login = new javax.swing.JMenuBar();
        jM_Help = new javax.swing.JMenu();
        jMI_Tutorial = new javax.swing.JMenuItem();
        jMI_AutoComplete = new javax.swing.JMenuItem();
        jMI_ValidEmail = new javax.swing.JMenuItem();
        jM_Language = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jP_Login.setBackground(new java.awt.Color(255, 253, 245));

        jL_Login.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jL_Login.setForeground(new java.awt.Color(91, 75, 56));
        jL_Login.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jL_Login.setText(JC_LanguageManager.getText("jL_Login"));
        jL_Login.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(91, 75, 56)));

        JL_UserTittle.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        JL_UserTittle.setForeground(new java.awt.Color(91, 75, 56));
        JL_UserTittle.setText(JC_LanguageManager.getText("jL_UserTittle"));

        JL_PaswordTittle.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        JL_PaswordTittle.setForeground(new java.awt.Color(91, 75, 56));
        JL_PaswordTittle.setText(JC_LanguageManager.getText("jL_Password"));

        jB_SigIn.setBackground(new java.awt.Color(91, 75, 56));
        jB_SigIn.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jB_SigIn.setForeground(new java.awt.Color(255, 253, 245));
        jB_SigIn.setText(JC_LanguageManager.getText("jB_SignIn"));
        jB_SigIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_SigInActionPerformed(evt);
            }
        });

        jTF_Email.setEditable(false);
        jTF_Email.setBackground(new java.awt.Color(255, 253, 245));
        jTF_Email.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jTF_Email.setForeground(new java.awt.Color(204, 204, 204));
        jTF_Email.setText(JC_LanguageManager.getText("jTF_Email"));
        jTF_Email.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(91, 75, 56)));
        jTF_Email.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTF_EmailMouseClicked(evt);
            }
        });
        jTF_Email.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTF_EmailKeyTyped(evt);
            }
        });

        jTF_SpaceBlank1.setEditable(false);
        jTF_SpaceBlank1.setBackground(new java.awt.Color(255, 253, 245));
        jTF_SpaceBlank1.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jTF_SpaceBlank1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(91, 75, 56)));

        jTF_SpaceBlank2.setEditable(false);
        jTF_SpaceBlank2.setBackground(new java.awt.Color(255, 253, 245));
        jTF_SpaceBlank2.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jTF_SpaceBlank2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(91, 75, 56)));

        jPF_Password.setEditable(false);
        jPF_Password.setBackground(new java.awt.Color(255, 253, 245));
        jPF_Password.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jPF_Password.setForeground(new java.awt.Color(204, 204, 204));
        jPF_Password.setText("jPasswordField1");
        jPF_Password.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(91, 75, 56)));
        jPF_Password.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPF_PasswordMouseClicked(evt);
            }
        });

        jL_Validation.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jL_Validation.setForeground(new java.awt.Color(91, 75, 56));
        jL_Validation.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jP_LoginLayout = new javax.swing.GroupLayout(jP_Login);
        jP_Login.setLayout(jP_LoginLayout);
        jP_LoginLayout.setHorizontalGroup(
            jP_LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_LoginLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jP_LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jP_LoginLayout.createSequentialGroup()
                        .addComponent(JL_PaswordTittle, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jP_LoginLayout.createSequentialGroup()
                        .addComponent(JL_UserTittle, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(369, 369, 369))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jP_LoginLayout.createSequentialGroup()
                        .addGroup(jP_LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jP_LoginLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jTF_SpaceBlank2, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(jPF_Password, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jP_LoginLayout.createSequentialGroup()
                                .addComponent(jTF_SpaceBlank1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(jTF_Email))
                            .addComponent(jL_Validation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jB_SigIn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(20, 20, 20))))
            .addGroup(jP_LoginLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jL_Login, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(10, 10, 10))
        );
        jP_LoginLayout.setVerticalGroup(
            jP_LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_LoginLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jL_Login, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(JL_UserTittle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jP_LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTF_Email, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTF_SpaceBlank1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jL_Validation, javax.swing.GroupLayout.DEFAULT_SIZE, 17, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(JL_PaswordTittle)
                .addGap(5, 5, 5)
                .addGroup(jP_LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPF_Password, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                    .addComponent(jTF_SpaceBlank2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(jB_SigIn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jM_Help.setText(JC_LanguageManager.getText("jM_Help"));

        jMI_Tutorial.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMI_Tutorial.setText(JC_LanguageManager.getText("jMI_Tutorial"));
        jMI_Tutorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMI_TutorialActionPerformed(evt);
            }
        });
        jM_Help.add(jMI_Tutorial);

        jMI_AutoComplete.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ENTER, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMI_AutoComplete.setText(JC_LanguageManager.getText("jMI_AutoComplete"));
        jMI_AutoComplete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMI_AutoCompleteActionPerformed(evt);
            }
        });
        jM_Help.add(jMI_AutoComplete);

        jMI_ValidEmail.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMI_ValidEmail.setText(JC_LanguageManager.getText("jMI_ValidEmail"));
        jMI_ValidEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMI_ValidEmailActionPerformed(evt);
            }
        });
        jM_Help.add(jMI_ValidEmail);

        jMB_Login.add(jM_Help);

        jM_Language.setText(JC_LanguageManager.getText("jM_Language"));
        jM_Language.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jM_LanguageMouseClicked(evt);
            }
        });
        jMB_Login.add(jM_Language);

        setJMenuBar(jMB_Login);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jP_Login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jP_Login, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private static Locale local;

    public static Locale getLocal() {
        return local;
    }

    public static void setLocal(Locale local) {
        JF_Login.local = local;
    }
    
    
    public void optionPane(String message) {

        JLabel labelEmergent = null;

        UIManager.put("OptionPane.background", new Color(255, 253, 245));
        UIManager.put("Panel.backgroud", new Color(91, 75, 56));

        labelEmergent = new JLabel(message, SwingConstants.CENTER);
        labelEmergent.setFont(new Font("Times New Roman", Font.BOLD, 16));
        labelEmergent.setForeground(new Color(91, 75, 56));
        JOptionPane.showMessageDialog(null, labelEmergent, "Message", JOptionPane.INFORMATION_MESSAGE);
    }

    public void isGray(JTextField textField) {

        if (!textField.isEditable()) {
            textField.setText("");
        }

        textField.setForeground(new Color(91, 75, 56));
        textField.setEditable(true);
    }

    public void validationEmail(String email, JLabel label) {

        Pattern range = Pattern.compile("^[_A-Za-z0-9-\\+]+(\\.[_A-Za-z0-9-]+)*@[A-Pa-p]+"
                + "(\\.[A-Pa-p]{3})$");

        Matcher comparation = range.matcher(email);

        if (comparation.matches()) {
            label.setText(JC_LanguageManager.getText("jL_ValidationTrue"));
        } else {
            label.setText(JC_LanguageManager.getText("jL_ValidationFalse"));
        }

    }

    private void jTF_EmailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTF_EmailMouseClicked
        isGray(jTF_Email);
    }//GEN-LAST:event_jTF_EmailMouseClicked

    private void jPF_PasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPF_PasswordMouseClicked
        isGray(jPF_Password);
    }//GEN-LAST:event_jPF_PasswordMouseClicked

    private void jMI_TutorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMI_TutorialActionPerformed


    }//GEN-LAST:event_jMI_TutorialActionPerformed

    private void jMI_AutoCompleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMI_AutoCompleteActionPerformed

        isGray(jTF_Email);
        isGray(jPF_Password);
        jPF_Password.setText(password);
        jTF_Email.setText(email);

        validationEmail(jTF_Email.getText(), jL_Validation);

    }//GEN-LAST:event_jMI_AutoCompleteActionPerformed

    private void jB_SigInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_SigInActionPerformed

        if ((new String(jPF_Password.getPassword()).equals(password)
                && jTF_Email.getText().equals(email)
                || jL_Validation.getText().equals("Invalid Email"))) {

            optionPane(JC_LanguageManager.getText("OP_SuccesfullLogin"));
            new JF_SendEmail().setVisible(true);
            dispose();
        } else {
            optionPane(JC_LanguageManager.getText("OP_UnsuccesfullLogin"));
        }

    }//GEN-LAST:event_jB_SigInActionPerformed

    private void jTF_EmailKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTF_EmailKeyTyped
        validationEmail(jTF_Email.getText(), jL_Validation);
    }//GEN-LAST:event_jTF_EmailKeyTyped

    private void jMI_ValidEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMI_ValidEmailActionPerformed

        optionPane(JC_LanguageManager.getText("OP_ValidEmail1"));
    }//GEN-LAST:event_jMI_ValidEmailActionPerformed

    private void jM_LanguageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jM_LanguageMouseClicked
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FlatLightLaf.setup();
                local = JC_LanguageManager.showLanguageSelectionDialog();
                JC_LanguageManager.setLanguage(local);
                dispose();
                new JF_Login().setVisible(true);
            }
        });
    }//GEN-LAST:event_jM_LanguageMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JF_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JF_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JF_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JF_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FlatLightLaf.setup();
                local = JC_LanguageManager.showLanguageSelectionDialog();
                JC_LanguageManager.setLanguage(local);
                new JF_Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JL_PaswordTittle;
    private javax.swing.JLabel JL_UserTittle;
    private javax.swing.JButton jB_SigIn;
    private javax.swing.JLabel jL_Login;
    private javax.swing.JLabel jL_Validation;
    private javax.swing.JMenuBar jMB_Login;
    private javax.swing.JMenuItem jMI_AutoComplete;
    private javax.swing.JMenuItem jMI_Tutorial;
    private javax.swing.JMenuItem jMI_ValidEmail;
    private javax.swing.JMenu jM_Help;
    private javax.swing.JMenu jM_Language;
    private javax.swing.JPasswordField jPF_Password;
    private javax.swing.JPanel jP_Login;
    private javax.swing.JTextField jTF_Email;
    private javax.swing.JTextField jTF_SpaceBlank1;
    private javax.swing.JTextField jTF_SpaceBlank2;
    // End of variables declaration//GEN-END:variables
}
