/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Class;

import Traduction.JC_LanguageManager;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;

import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author migue
 */
public class JF_Registry extends javax.swing.JFrame {

 private DefaultTableModel model;


    
    
    /**
     * Creates new form JF_SentEmail
     */
    public JF_Registry() {
        initComponents();
        setLocationRelativeTo(null); // Centrar la ventana en la pantalla
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        
        model = (DefaultTableModel)jTable1.getModel();

 
        loadEmailHistory();  // Cargar historial al iniciar la aplicación
    }
    

   
       
  public void saveEmailLog(String from, String to, String subject, String content, String attachment) {
      
      if (attachment == null || attachment.isEmpty()) {
        attachment = ""; 
    }
    try (FileWriter fw = new FileWriter("historial.csv", true);
         PrintWriter pw = new PrintWriter(fw)) {
        
        String timestamp = LocalDateTime.now().format(DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss"));
        
        // Crear una línea para guardar en el archivo CSV con el archivo adjunto
        String emailRecord = String.join(",", from, to, subject, content.replace("\n", " "), attachment, timestamp);
        
        // Escribir la línea en el archivo CSV
        pw.println(emailRecord);
        
        // Actualizar la tabla con el nuevo correo enviado, también con el archivo adjunto
        model.addRow(new Object[]{from, to, subject, content, attachment, timestamp});
        
    } catch (IOException e) {
        e.printStackTrace();
    }
}
    
public void loadEmailHistory() {
    File file = new File("historial.csv");
    if (!file.exists()) {
        System.out.println("Archivo no encontrado");
        
        return;
    }

    try (BufferedReader br = new BufferedReader(new FileReader(file))) {
        String line;
        while ((line = br.readLine()) != null) {
            String[] data = line.split(",", 6); // Ahora se espera que haya 6 columnas (incluyendo el archivo adjunto)
            if (data.length == 6) {
                model.addRow(data); // Añadir fila a la tabla
            }
        }
    } catch (IOException e) {
        e.printStackTrace();
    }
}




    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jP_SentEmail = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jMB_SendEmail = new javax.swing.JMenuBar();
        jM_Back = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jP_SentEmail.setBackground(new java.awt.Color(255, 253, 245));

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jTable1.setBackground(new java.awt.Color(255, 253, 245));
        jTable1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "", "", "", "", "", ""
            }
        ));
        jScrollPane2.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setHeaderValue(JC_LanguageManager.getText("column_sender"));
            jTable1.getColumnModel().getColumn(1).setHeaderValue(JC_LanguageManager.getText("column_recipient"));
            jTable1.getColumnModel().getColumn(2).setHeaderValue(JC_LanguageManager.getText("column_subject"));
            jTable1.getColumnModel().getColumn(3).setHeaderValue(JC_LanguageManager.getText("column_content"));
            jTable1.getColumnModel().getColumn(4).setHeaderValue(JC_LanguageManager.getText("column_attachment"));
            jTable1.getColumnModel().getColumn(5).setHeaderValue(JC_LanguageManager.getText("column_date"));
        }

        jScrollPane1.setViewportView(jScrollPane2);

        javax.swing.GroupLayout jP_SentEmailLayout = new javax.swing.GroupLayout(jP_SentEmail);
        jP_SentEmail.setLayout(jP_SentEmailLayout);
        jP_SentEmailLayout.setHorizontalGroup(
            jP_SentEmailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_SentEmailLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 708, Short.MAX_VALUE)
                .addContainerGap())
        );
        jP_SentEmailLayout.setVerticalGroup(
            jP_SentEmailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_SentEmailLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        jM_Back.setText(JC_LanguageManager.getText("jM_Back"));
        jM_Back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jM_BackMouseClicked(evt);
            }
        });
        jMB_SendEmail.add(jM_Back);

        setJMenuBar(jMB_SendEmail);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jP_SentEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jP_SentEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void jM_BackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jM_BackMouseClicked
      
       dispose();
    }//GEN-LAST:event_jM_BackMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JF_Registry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JF_Registry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JF_Registry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JF_Registry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JF_Registry().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMB_SendEmail;
    private javax.swing.JMenu jM_Back;
    private javax.swing.JPanel jP_SentEmail;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
